---
name: PHP Composer + PHPStan

on:
  push:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - 'notest/**'

  pull_request:
    branches-ignore:
      # notest branches to ignore testing of partial online commits
      - 'notest/**'

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    # Limit the running time
    timeout-minutes: 10
    strategy:
      matrix:
        operating-system:
          - "ubuntu-latest"
        php-version: ['5.3', '5.6', '7.0', '7.2', '7.3', '7.4']
        # 7.1 is not checked, as due to https://bugs.php.net/bug.php?id=73803        
        # ZipArchive class has public properties, that are not visible via reflection.
        # Therefore using tools like PHPStan generates error: Access to an undefined property ZipArchive::$numFiles. in class\MyAdminProcess

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP ${{ matrix.php-version }} Test on ${{ matrix.operating-system }}"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2, phpstan
          # Note: phpstan call fails for PHP<7.1
        env:
          # fixes Error: Could not authenticate against github.com
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/actions/cache
      # A repository can have up to 5GB of caches. Once the 5GB limit is reached, older caches will be evicted based on when the cache was last accessed.
      # Caches that are not accessed within the last week will also be evicted.
      - name: Cache composer dependencies
        uses: actions/cache@v3
        id: vendor-cache
        with:
          # path to Checkout working directory is /home/runner/work/repo-name/repo-name , so just add /vendor/
          path: ${{ github.workspace }}/vendor/
          # Use composer.json for key, if composer.lock is not committed.
          key: ${{ runner.os }}-PHP${{ matrix.php-version }}-vendor-${{ hashFiles('**/composer.json') }}
          # key: ${{ runner.os }}-PHP${{ matrix.php-version }}-vendor-${{ hashFiles('**/composer.lock') }}
          #restore-keys: ${{ runner.os }}-PHP${{ matrix.php-version }}-vendor-

      - name: Cache dist composer dependencies
        uses: actions/cache@v3
        id: dist-vendor-cache
        with:
          # path to Checkout working directory is /home/runner/work/repo-name/repo-name , so just add /vendor/
          path: ${{ github.workspace }}/dist/vendor/
          # Use composer.json for key, if composer.lock is not committed.
          key: ${{ runner.os }}-PHP${{ matrix.php-version }}-dist-vendor-${{ hashFiles('**/dist/composer.json') }}
          # key: ${{ runner.os }}-PHP${{ matrix.php-version }}-vendor-${{ hashFiles('**/composer.lock') }}
          #restore-keys: ${{ runner.os }}-PHP${{ matrix.php-version }}-dist-vendor-

      - name: Validate composer.json and composer.lock
        if: ${{ steps.vendor-cache.outputs.cache-hit != 'true' }}
        run: composer validate

      - name: Install no-dev dependencies
        if: ${{ steps.vendor-cache.outputs.cache-hit != 'true' }}
        run: composer update --no-dev --prefer-dist --no-progress
      
      - name: Install dev dependencies
        if: ${{ steps.vendor-cache.outputs.cache-hit != 'true' }}
        run: composer update --prefer-dist --no-progress

      # PHPStan works for PHP/7.1+ so it can't even be in composer.json
      - name: "Composer phpstan-webmozart-assert (library)"
        if: ${{ matrix.php-version >= '7.1' && steps.vendor-cache.outputs.cache-hit != 'true' }}
        run: |
          # Only phpstan/phpstan-webmozart-assert + phpstan/phpstan added
          composer require --dev phpstan/phpstan-webmozart-assert --prefer-dist --no-progress
      - name: "PHPStan webmozart-assert (library)"
        # alternative syntax # if: ${{ matrix.php-version != '5.3' && matrix.php-version != '5.6' }}
        if: ${{ matrix.php-version >= '7.1' }}
        run: |
          # Note that phpstan/phpstan is required above but not used below (as shivammathur/setup-php tool is used)
          phpstan --configuration=conf/phpstan.webmozart-assert.neon analyse --no-interaction --no-progress .
